<Project Sdk="Aspire.AppHost.Sdk/13.4.6">


  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>2fbc1cf9-c051-499e-b228-084ee6732f8d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Azure.Functions" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Functions\Spurious2.Processors.Inventories\Spurious2.Processors.Inventories.csproj" />
    <ProjectReference Include="..\..\Functions\Spurious2.Processors.Products\Spurious2.Processors.Products.csproj" />
    <ProjectReference Include="..\..\Functions\Spurious2.Processors.Stores\Spurious2.Processors.Stores.csproj" />
    <ProjectReference Include="..\..\Functions\Spurious2.Scraper\Spurious2.Scraper.csproj" />
    <ProjectReference Include="..\Spurious2.MigrationService\Spurious2.MigrationService.csproj" />
    <ProjectReference Include="..\Spurious2\Spurious2.csproj" />
  </ItemGroup>

</Project>
