// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spurious2.Infrastructure.Models;

public partial class Inventory
{
    public int ProductId { get; set; }

    public int StoreId { get; set; }

    public int Quantity { get; set; }

    public virtual Store Store { get; set; }
}