// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Spurious2.Infrastructure.Models;

public partial class SpuriousContext : DbContext
{
    public SpuriousContext(DbContextOptions<SpuriousContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Core2.Stores.Inventory> Inventories { get; set; }

    public virtual DbSet<Core2.Stores.Store> Stores { get; set; }

    public virtual DbSet<Core2.Subdivisions.Subdivision> Subdivisions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Core2.Stores.Inventory>(entity =>
        {
            entity.HasKey(e => new { e.ProductId, e.StoreId });

            entity.ToTable("Inventory");

            entity.HasOne(d => d.Store).WithMany(p => p.Inventories)
                .HasForeignKey(d => d.StoreId)
                .HasConstraintName("FK_Inventory_Store");
        });

        modelBuilder.Entity<Core2.Stores.Store>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("stores_pkey");

            entity.ToTable("Store");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.City).HasColumnType("text");
            entity.Property(e => e.StoreName).HasColumnType("text");
            entity.Property(e => e.Location).HasColumnType("geography");

        });

        modelBuilder.Entity<Core2.Subdivisions.Subdivision>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("firstkey");

            entity.ToTable("Subdivision");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.AlcoholDensity).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.BeerDensity).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.Province).HasMaxLength(255);
            entity.Property(e => e.SpiritsDensity).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.SubdivisionName).HasMaxLength(255);
            entity.Property(e => e.WineDensity).HasColumnType("decimal(9, 2)");
            entity.Property(e => e.GeographicCentre).HasColumnType("geography");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}