// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Spurious2.Infrastructure.Models;

public partial class Store
{
    public int Id { get; set; }

    public string StoreName { get; set; }

    public string City { get; set; }

    public int? BeerVolume { get; set; }

    public int? WineVolume { get; set; }

    public int? SpiritsVolume { get; set; }

    public virtual ICollection<Inventory> Inventories { get; set; } = new List<Inventory>();
}