version: '3.4'

services:
  spurious2:
    image: ${DOCKER_REGISTRY-}spurious2
    build:
      context: .
      dockerfile: WebCore/Spurious2/Dockerfile
    volumes:
      # map the dotnet user-secret folder
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  spurious2-seq:
    image: datalust/seq:latest
    container_name: spurious2.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  spurious2-sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: spurious2.sql
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=sqlpwd2@
  