version: '3.4'

services:
  spurious2:
    image: ${DOCKER_REGISTRY-}spurious2
    build:
      context: .
      dockerfile: WebCore/Spurious2/Dockerfile
    volumes:
      # map the dotnet user-secret folder
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  spurious2-seq:
    image: datalust/seq:latest
    container_name: spurious2.seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80

  spurious2-sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: spurious2.sql
    ports: # not actually needed, because the two services are on the same network.
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=sqlpwd2@

  spurious2function2:
    image: ${DOCKER_REGISTRY-}spurious2function2
    build:
      context: .
      dockerfile: Spurious2.Function2/Dockerfile
    volumes:
      # map the dotnet user-secret folder
      - $APPDATA/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  spurious2-azurite:
    image: "mcr.microsoft.com/azure-storage/azurite"  
    container_name: spurious2.azurite
    ports:
        - 10004:10000
        - 10005:10001
        - 10002:10002
    command: "azurite -l /data --blobHost 0.0.0.0 --blobPort 10000 --queueHost 0.0.0.0 --queuePort 10001 --tableHost 0.0.0.0 --tablePort 10002 --skipApiVersionCheck --disableProductStyleUrl"