<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Inventories-48e97bc8-ea9f-45ba-b609-3436dff1981d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
    <PackageReference Include="Aspire.Azure.Storage.Queues" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WebCore\Spurious2.Core2\Spurious2.Core2.csproj" />
    <ProjectReference Include="..\..\WebCore\Spurious2.Infrastructure\Spurious2.Infrastructure.csproj" />
    <ProjectReference Include="..\..\WebCore\Spurious2.ServiceDefaults\Spurious2.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
