<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Products-3aa7c59a-8fd4-4c0e-affe-dea01ae5cdb7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
    <PackageReference Include="Aspire.Azure.Storage.Queues" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\WebCore\Spurious2.Infrastructure\Spurious2.Infrastructure.csproj" />
    <ProjectReference Include="..\..\WebCore\Spurious2.ServiceDefaults\Spurious2.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
