/**
 * Spurious2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type AlcoholType = '0' | '1' | '2' | '3';

export type CRSType = '0' | '1' | '2';

export interface DensityInfo {
  shortName?: string;
  title?: string;
  address?: string;
}


export type GeoJSONObjectType = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8';

export interface ICRSObject {
  type?: CRSType;
}


export interface IPosition {
  altitude?: number;
  latitude?: number;
  longitude?: number;
}


export interface Inventory {
  alcoholType?: AlcoholType;
  volume?: number;
}


export interface Point {
  bbox?: Array<number>;
  crs?: ICRSObject;
  type?: GeoJSONObjectType;
  coordinates?: IPosition;
}


export interface Store {
  id?: number;
  locationCoordinates?: Point;
  name?: string;
  city?: string;
  inventories?: Array<Inventory>;
}


export interface Subdivision {
  name?: string;
  population?: number;
  requestedDensityAmount?: number;
  boundaryLink?: string;
  centreCoordinates?: Point;
  storesLink?: string;
  id?: number;
}

