//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spurious2.Core2.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spurious2.Core2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,StoreName,LocationWkt,City,SubdivisionId,BeerVolume,WineVolume,SpiritsVolume
        ///1,Highway 401 &amp; Weston,POINT (-79.531 43.7127),Toronto-North York,3520005,24401974,14880638,18488286
        ///2,St. Clair &amp; Bathurst,POINT (-79.4154 43.684),Toronto,3520005,7247215,1204070,1032215
        ///3,Dundas &amp; Dovercourt,POINT (-79.4235 43.6496),Toronto,3520005,8711727,6164020,8772335
        ///4,Danforth &amp; Broadview,POINT (-79.3561 43.6769),Toronto,3520005,14198173,15580122,7268215
        ///5,Queen &amp; Coxwell,POINT (-79.315 43.6669),Toronto,3520005,1179 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cachedstores {
            get {
                return ResourceManager.GetString("cachedstores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id,Population,SubdivisionName,AlcoholDensity,BeerDensity,Province,SpiritsDensity,WineDensity,BoundaryWkt,CentreWkt
        ///3501005,13330,South Glengarry,992.34,572.91,Ontario,249.83,169.60,&quot;POLYGON ((-74.653 45.0192, -74.6444 45.0228, -74.6385 45.025, -74.6371 45.0255, -74.6339 45.0266, -74.6285 45.029, -74.6249 45.0304, -74.6182 45.0329, -74.6135 45.0347, -74.6075 45.0371, -74.6074 45.0372, -74.6074 45.0372, -74.6046 45.0383, -74.5965 45.0414, -74.5923 45.0417, -74.5843 45.0423, -74.5793 45.0427, -74.5758 45.0431 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cachedsubdivs {
            get {
                return ResourceManager.GetString("cachedsubdivs", resourceCulture);
            }
        }
    }
}
